### ISSUE TITLE
duplicate symbol __Z12CallbackProcjlll in  Unrar4iOS.o

### ISSUE THREAD

**Issue by lzbgithubcode** [saru2020/SARUnArchiveANY#11]
compile question in Devive  
1、duplicate symbol __Z12CallbackProcjlll in  Unrar4iOS.o  
2、12 duplicate symbols for architecture arm64

**Comment by saru2020** [comment]
Fixed 373d33aadf926f13e312b10b4aa6ef9c013dce44
