### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xiuqiao** [saru2020/SARUnArchiveANY#8]
SARUnArchiveANY/External/LZMASDK/CpuArch.c: Instruction requires: Not 64-bit mode

use by cocoapods.

The CpuArch.h  install by cocoapods different with the github project file.

**Comment by ZuYuanZhou** [comment]
same problem.

**Comment by JolieYang** [comment]
me too

**Comment by saru2020** [comment]
Fixed!
