### ISSUE TITLE
.7z can you  support password？

### ISSUE THREAD

**Issue by mujundong0827** [saru2020/SARUnArchiveANY#9]
.7z can you  support password？

**Comment by saru2020** [comment]
Hey,

Not sure if i would get time to do it.
This has been on my TODO list for a very long time now.
Am thinking of using [this](https://github.com/OlehKulykov/LzmaSDKObjC) library for 7z unarchiving.
Let me know, if you could do it & raise a pull request, may be. If not, then may be i should allocate sometime aside for it.

Thanks for raising it. Its great to hear that people are actually using it and its worth the effort.

**Comment by mujundong0827** [comment]
I'd like to write their own support.7 z password But my ability is insufficient.I am so sad

**Comment by saru2020** [comment]
Finally, got it done. ba6d12e95188da99540e728cd52c60173195ebf9
